#include "databaseComs.h"
#include <iostream>
#include <QCoreApplication>
#include <QtSql>
#include <QSqlDatabase>
#include "entityList.h"
#include "itemlist.h"

DatabaseComs::DatabaseComs(std::string n) {
    fileName = n;
    db = QSqlDatabase::addDatabase("QSQLITE");
    db.setDatabaseName(QString::fromStdString(n));
    //std::cout << "Database opened\n";

    if (db.open()){
    	//std::cout << "Database opened\n";
    }
    else{
	std::cout << "Database failed to open\n";
    }
    createTables();
}

DatabaseComs::~DatabaseComs(){
    if(db.isOpen()){
        db.close();
        // std::cout << "Database closed\n";
    }
}

int DatabaseComs::execute(std::string sql){
    QSqlQuery query;

    if (!query.exec(QString::fromStdString(sql))) {
        std::cerr << "SQL Error: "
                  << query.lastError().text().toStdString()
                  << std::endl;
        return -1;
    }

    //return true;
    return query.lastInsertId().toInt();
}

void DatabaseComs::createTables(){
    std::string karakter =
        "CREATE TABLE IF NOT EXISTS Character ("
        "characterId	INTEGER,"
        "name	TEXT,"
        "totalKillCount	INTEGER,"
        "itemMostUsed	TEXT,"
        "entityMostUsed	TEXT,"
        "PRIMARY KEY(characterId)"
        ");"; // 'karakter' used instead of 'character' to avoid potential keyword conflicts
    
    std::string entity =
        "CREATE TABLE IF NOT EXISTS Entity ("
        "entityId   INTEGER,"
        "characterId	INTEGER,"
        "entityIdx	INTEGER,"
        "PRIMARY KEY(entityId),"
        "FOREIGN KEY(characterId) REFERENCES Character(characterId)"
        ");";

    std::string entItem =
        "CREATE TABLE IF NOT EXISTS EntItem ("
        "itemIdx	INTEGER,"
        "entityId	INTEGER,"
        "itemKills	INTEGER,"
        "itemUses   INTEGER,"
        "FOREIGN KEY(entityId) REFERENCES Entity(entityId)"
        ");";
    
    std::string charItem =
        "CREATE TABLE IF NOT EXISTS CharItem ("
        "itemIdx	INTEGER,"
        "characterId	INTEGER,"
        "FOREIGN KEY(characterId) REFERENCES Character(characterId)"
        ");";
    
    execute(karakter);
    execute(entity);
    execute(entItem);
    execute(charItem);
}

void DatabaseComs::addSave(Character& karakter){
    std::string command;

    // Add character
    command = "INSERT INTO Character "
              "(name, totalKillCount, itemMostUsed, entityMostUsed) "
              "VALUES ('";
    //int charIdx = 0;
    //command += std::to_string(charIdx) + ", '"; // characterId
    command += karakter.getName() + "', "; // characterName
    command += std::to_string(karakter.getKillCount()) + ", '"; // totalKillCount
    command += karakter.getMostUsedItem() + "', '"; // itemMostUsed
    command += karakter.getMostUsedEntity() + "');"; // entityMostUsed
    //std::cout << command << "\n";
    int charIdx = execute(command); // get autogenerated Id

    // Add monsters
    EntityList el;
    ItemList il;
    for (int i = 0; i < karakter.collection.size(); ++i){
        command = "INSERT INTO Entity "
                  "(characterId, entityIdx) "
                  "VALUES (";
        //int entId = 0; // must be the integer after the integer before
        //command += std::to_string(entId) + ", "; // entityId
        command += std::to_string(charIdx) + ", "; // characterId
        int entIdx;
        for (int j = 0; j < el.list.size(); ++j){
            if (karakter.collection[i].getName() == el.list[j].getName()){
                entIdx = j;
            }
        }
        command += std::to_string(entIdx) + ");"; // entityIdx
	    //std::cout << command << "\n";
        int entId = execute(command); // get autogenerated Id

        // Add monster items
        for (int j = 0; j < karakter.collection[i].getEquippedItems().size(); ++j){
            command = "INSERT INTO EntItem "
                      "VALUES (";
            int iteIdx;
            for (int k = 0; k < il.list.size(); ++k){
                if (il.list[k].getName() == karakter.collection[i].getEquippedItems()[j].getName()){
                    iteIdx = k;
                }
            }
            command += std::to_string(iteIdx) + ", "; // itemIdx
            command += std::to_string(entId) + ", "; // entityId
            command += std::to_string(karakter.collection[i].getEquippedItems()[j].getKills()) + ", "; // itemKills
            command += std::to_string(karakter.collection[i].getEquippedItems()[j].getUses()) + ");"; // itemUses
            //std::cout << command << "\n";
            execute(command);
        }
    }
    
    // Add character items
    for (int i = 0; i < karakter.getItems().size(); ++i){
        command = "INSERT INTO CharItem "
                  "VALUES (";
        int iteIdx;
        for (int j = 0; j < il.list.size(); ++j){
            if (il.list[j].getName() == karakter.getItems()[i].getName()){
                iteIdx = j;
            }
        }
        command += std::to_string(iteIdx) + ", "; // itemIdx
        command += std::to_string(charIdx) + ");"; // characterId
        //std::cout << command << "\n";
        execute(command);
    }
}

void DatabaseComs::updateSave(int charID, Character& karakter){
    std::string command;

    // Update character
    /*query.prepare("UPDATE Character "
                  "SET characterName = (?)"
                  "SET totalKillCount = (?)"
                  "SET itemMostUsed = (?)"
                  "SET entityMostUsed = (?)"
                  "WHERE characterId = (?)");*/
    command = "UPDATE Character ";
    //query.addBindValue(QString::fromStdString(karakter.getName())); // characterName
    command += "SET name = '" + karakter.getName() + "', "; // characterName
    //query.addBindValue(karakter.getKillCount()); // totalKillCount
    command += "totalKillCount = " + std::to_string(karakter.getKillCount()) + ", "; // totalKillCount
    //query.addBindValue(QString::fromStdString(karakter.getMostUsedItem())); // itemMostUsed
    command += "itemMostUsed = '" + karakter.getMostUsedItem() + "', "; // itemMostUsed
    //query.addBindValue(QString::fromStdString(karakter.getMostUsedEntity())); // entityMostUsed
    command += "entityMostUsed = '" + karakter.getMostUsedEntity() + "' "; // entityMostUsed
    //query.addBindValue(charID); // characterId
    command += "WHERE characterId = " + std::to_string(charID) + ";"; // characterId
    //qDebug << query.exec();
    //query.exec();
    execute(command);

    // Remove monster items
    command = "DELETE FROM EntItem WHERE entityId = (SELECT entityId FROM Entity WHERE characterId = ";
    command += std::to_string(charID) + " AND entityId = ";
    for (int i = 1; i < 9; ++i){
        std::string newCommand = command + std::to_string(i) + ");";
        execute(newCommand);
    }

    // Remove monsters and items
    command = "DELETE FROM Entity WHERE characterId = " + std::to_string(charID);
    execute(command);
    command = "DELETE FROM CharItem WHERE characterId = " + std::to_string(charID);
    execute(command);

    // Update monsters
    EntityList el;
    ItemList il;
    for (int i = 0; i < karakter.collection.size(); ++i){
        /*query.prepare("UPDATE Entity "
                      "SET entityIdx = (?)"
                      "WHERE characterId = (?)"
                      "AND WHERE entId = (?)");*/
        command = "INSERT INTO Entity (characterId, entityIdx)  VALUES (";
        int entIdx;
        for (int j = 0; j < el.list.size(); ++j){
            if (karakter.collection[i].getName() == el.list[j].getName()){
                entIdx = j;
            }
        }
        //int entId = 0; // must be the integer after the integer before
        //query.addBindValue(entId); // entityId
        //command += std::to_string(entId) + ", "; // entityId
        //query.addBindValue(charID); // characterId
        command += std::to_string(charID) + ", "; // characterId
        //query.addBindValue(entIdx); // entityIdx
        command += std::to_string(entIdx) + ");"; // entityIdx
        //query.exec();
        int entId = execute(command);

        // Update monster items
        for (int k = 0; k < karakter.collection[i].getEquippedItems().size(); ++k){
            /*query.prepare("UPDATE EntItem "
                          "SET itemIdx = (?)"
                          "SET itemKills = (?)"
                          "SET itemUses = (?)"
                          "WHERE entityId = (?)"
                          "AND WHERE characterId = (?)");*/
            command = "INSERT INTO EntItem VALUES (";
            int iteIdx;
            for (int j = 0; j < il.list.size(); ++j){
                if (il.list[j].getName() == karakter.collection[i].getEquippedItems()[k].getName()){
                    iteIdx = j;
                }
            }
            //query.addBindValue(iteIdx); // itemIdx
            command += std::to_string(iteIdx) + ", "; // itemIdx
            //query.addBindValue(charID); // characterId
            command += std::to_string(entId) + ", "; // characterId
            //query.addBindValue(karakter.getItems()[i].getKills()); // itemKills
            command += std::to_string(karakter.collection[i].getEquippedItems()[k].getKills()) + ", "; // itemKills
            //query.addBindValue(karakter.getItems()[i].getUses()); // itemUses
            command += std::to_string(karakter.collection[i].getEquippedItems()[k].getUses()) + ");"; // itemKills
            //query.exec();
            execute(command);
        }
    }
    
    // Update character items
    for (int i = 0; i < karakter.getItems().size(); ++i){
        /*query.prepare("UPDATE CharItem "
                      "SET itemIdx = (?)"
                      "WHERE characterId = (?)");*/
        command = "INSERT INTO CharItem VALUES (";
        int iteIdx;
        for (int j = 0; j < il.list.size(); ++j){
            if (il.list[j].getName() == karakter.getItems()[i].getName()){
                iteIdx = j;
            }
        }
        //query.addBindValue(iteIdx); // itemIdx
        command += std::to_string(iteIdx) + ", "; // itemIdx
        //query.addBindValue(charID); // characterId
        command += std::to_string(charID) + ");"; // characterId
        //query.exec();
        execute(command);
    }
}

std::vector<Character> DatabaseComs::getCharacters(){
    QSqlQuery query;
    std::string command = "SELECT characterId, name, totalKillCount FROM Character";
    std::vector<int> charIds;
    std::vector<std::string> charNames;
    std::vector<int> killCounts;
    query.exec(QString::fromStdString(command));
    while(query.next()){ // extract data
        charIds.push_back(query.value(0).toInt()); // characterId
        charNames.push_back(query.value(1).toString().toStdString()); // name
        killCounts.push_back(query.value(2).toInt()); // totalKillCount
    }
    std::vector<Character> charList;
    for (int i = 0; i < charIds.size(); ++i){ // build characters
        Character newChar;
        newChar.setName(charNames[i]); // Set name for character
        charList.push_back(newChar); // Add new character to list
        charList[i].addKill(killCounts[i]);
    }
    assignItemsToChars(charList, charIds); // Add items to character // Needs testing
    assignEntities(charList, charIds); // Add allies to character // Needs testing
    // TODO: Add entities to characters
    return charList;
}

void DatabaseComs::assignItemsToChars(std::vector<Character>& charList, std::vector<int> charIdList){ // Needs testing
    QSqlQuery query;
    ItemList il;
    for (int i = 0; i < charIdList.size(); ++i){
        std::vector<int> itemIdx;
        std::string command = "SELECT itemIdx FROM CharItem WHERE characterId = " + std::to_string(charIdList[i]);
        query.exec(QString::fromStdString(command));
        while(query.next()){
            itemIdx.push_back(query.value(0).toInt()); // itemIdx
        }
        for (int j = 0; j < itemIdx.size(); ++j){
            charList[i].addItem(il.list[itemIdx[j]]);
        }
    }
}

void DatabaseComs::assignEntities(std::vector<Character>& charList, std::vector<int> charIdList){ // Needs testing
    QSqlQuery query;
    EntityList el;
    for (int i = 0; i < charIdList.size(); ++i){ // Run through each characterId
        std::vector<int> entityIdx;
        std::vector<int> entId;
        std::string command = "SELECT entityIdx, entityId FROM Entity WHERE characterId = " + std::to_string(charIdList[i]);
        query.exec(QString::fromStdString(command));
        while(query.next()){
            entityIdx.push_back(query.value(0).toInt()); // entityIdx
            entId.push_back(query.value(1).toInt()); // entityId
        }
        for (int j = 0; j < entityIdx.size(); ++j){ // Run through each entityId
            Entity monster = el.list[entityIdx[j]];
            assignItemsToEnt(monster, entId[j]);
            charList[i].addMonster(monster,true); // Add entity to character
        }
    }
}

void DatabaseComs::assignItemsToEnt(Entity& ent, int entId){ // Needs testing
    QSqlQuery query;
    std::string command = "SELECT itemIdx, itemKills, itemUses FROM EntItem WHERE entityId = " + std::to_string(entId);
    std::vector<Item> items;
    ItemList il;
    query.exec(QString::fromStdString(command));
    while(query.next()){
        Item ting = il.list[query.value(0).toInt()]; // itemIdx
        ting.addKill(query.value(1).toInt()); // itemKills
        ting.addUse(query.value(2).toInt()); // itemUses
        items.push_back(ting);
    }
    for (int i = 0; i < items.size(); ++i){ // Add each item to entity
        ent.equipItem(items[i]);
    }
}